CONFIG_ZMK_POINTING=y

# The pinnacle driver also requires this to include sleep code
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_BATTERY_REPORTING=y

# Enter deep sleep https://zmk.dev/docs/features/low-power-states
CONFIG_ZMK_SLEEP=y

# 60-minute idle sleep (default 15) — only slightly more power, much better UX
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# 30s idle for trackpad power management
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Enables proper sleep notifications into the cirque driver + soft-off feature
CONFIG_ZMK_PM_SOFT_OFF=y
